# Generated by Django 6.1 on 2026-08-08 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_customuser_is_online_customuser_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepic',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
