"""
Django settings for chattingapp project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ----------------------------------------------------------------------
# SECURITY
# ----------------------------------------------------------------------
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure--zvwsu%2&*9_+3l7(^y=*)(^+ekz7ft0heul37$_(fk7!0w7s$'
)

# DEBUG is controlled by an env var – set to "False" in production
DEBUG = os.environ.get('DEBUG', 'True').lower() in ['true', '1', 'yes']

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '*').split(',')

# Render terminates TLS at the load balancer – tell Django to trust the
# X-Forwarded-Proto header so CSRF sees requests as HTTPS.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# CSRF trusted origins – we add the Render hostname dynamically.
CSRF_TRUSTED_ORIGINS = [
    'https://django-chat-application-71vb.onrender.com',
]
render_external_hostname = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if render_external_hostname:
    CSRF_TRUSTED_ORIGINS.append(f'https://{render_external_hostname}')


# ----------------------------------------------------------------------
# APPLICATIONS
# ----------------------------------------------------------------------
INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'login.apps.LoginConfig',
    'chat.apps.ChatConfig',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
]

# Cloudinary storage is only needed when the env vars are present.
# We add the apps conditionally so local dev (without Cloudinary) stays clean.
if os.environ.get('CLOUDINARY_CLOUD_NAME'):
    INSTALLED_APPS.insert(0, 'cloudinary_storage')   # must come before staticfiles
    INSTALLED_APPS.append('cloudinary')


# ----------------------------------------------------------------------
# MIDDLEWARE
# ----------------------------------------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',   # serves static files in prod
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ----------------------------------------------------------------------
# URL / WSGI / ASGI
# ----------------------------------------------------------------------
ROOT_URLCONF = 'chattingapp.urls'
WSGI_APPLICATION = 'chattingapp.wsgi.application'
ASGI_APPLICATION = 'chattingapp.asgi.application'


# ----------------------------------------------------------------------
# CHANNELS (USE REDIS IN PRODUCTION, IN-MEMORY ONLY FOR LOCAL DEV)
# ----------------------------------------------------------------------
# In production Render provides a REDIS_URL via the Redis add‑on.
# If the variable is missing we fall back to the in‑memory layer (useful for
# local development where you might not have Redis running).
if os.environ.get('REDIS_URL'):
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [os.environ.get('REDIS_URL')],
            },
        },
    }
else:
    # Local dev fallback – **do NOT use in production!**
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }


# ----------------------------------------------------------------------
# DATABASE (uses DATABASE_URL from Render Postgres add‑on)
# ----------------------------------------------------------------------
DATABASES = {
    'default': dj_database_url.config(
        default='postgres://postgres:Hitman%404165@localhost:5432/newchatdb',
        conn_max_age=600,
        conn_health_checks=True,
    )
}

AUTH_USER_MODEL = 'login.CustomUser'


# ----------------------------------------------------------------------
# PASSWORD VALIDATION
# ----------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ----------------------------------------------------------------------
# INTERNATIONALIZATION
# ----------------------------------------------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# ----------------------------------------------------------------------
# STATIC FILES (CSS, JavaScript, Images)
# ----------------------------------------------------------------------
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Use WhiteNoise for efficient static file serving in production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# ----------------------------------------------------------------------
# MEDIA FILES (USER‑UPLOADED CONTENT)
# ----------------------------------------------------------------------
# We switch between Cloudinary (production) and local storage (dev)
# based on the presence of CLOUDINARY_CLOUD_NAME.
if os.environ.get('CLOUDINARY_CLOUD_NAME'):
    # -------- PRODUCTION: CLOUDINARY ----------
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME'),
        'API_KEY':    os.environ.get('CLOUDINARY_API_KEY'),
        'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET'),
    }
    # Tell Django to use Cloudinary for ALL file uploads
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
else:
    # -------- LOCAL DEVELOPMENT: LOCAL FILESYSTEM ----------
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'


# ----------------------------------------------------------------------
# AUTHENTICATION REDIRECTS
# ----------------------------------------------------------------------
LOGIN_URL = 'login-view'
LOGIN_REDIRECT_URL = 'chat:home-view'


# ----------------------------------------------------------------------
# DEFAULT PRIMARY KEY FIELD
# ----------------------------------------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
